New functions to consider to replace part of add_to_index
SETI/rms-data-projects pull request #50
Opened 2023-06-21 22:45 UTC by esimpsons3ti

bundleset.py now contains two new functions that replace the functionality of add_to_index. When these functions have been corrected and passed in, they will be implemented into the other tools (bundle.py and collections.py). Functionality for bundleset.py has been confirmed.

2023-08-04 04:56 UTC, matthewtiscareno requested changes
This is a great step forward.  I have verified that function is correct, and I love the modular format with concise `main` functions and the detail mostly in `pds4_index_tools.py`

I have a number of comments, some of which are specific and some of which are asking that we considering a certain point.  Let's discuss what to do with each item before you spend much time making changes.

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +        if lid in member_index:
Doesn't this assume that the dictionary key is the LID?  I seem to remember discussing the idea that instead we match this with the LID field of the dictionary.  Is there a reason we decided not to do that?

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
Shouldn't this be `bundleset_name`?

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +    """Search the xml file for the LID.
"the xml" ==> "a bundle.xml" 
Right?  This function is specific to bundle.xml files, isn't it?

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +def get_collection_entries(collection_root, namespaces, collection_directory):
Perhaps this function should be called something like `get_collprod_filepath`.  That's what it does, right?  It doesn't actually parse the collection product for its entries. 

While writing this comment, I invented `collprod` as perhaps an improvement over spelling out `collection_product`.  What do you think?

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +    """Populate the member_index with the collection product information.
"the collection product information" ==> "information about collection members"
Right?

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +def collection_crossmatch(fullpaths, member_index, directory,
Is there a reason not to merge `bundle_crossmatch` and `collection_crossmatch`?

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +        if lid in member_index:
See comment in `bundle_crossmatch` about using the LID as the dictionary key.

2023-08-04 04:56 UTC, matthewtiscareno commented on indextools/pds4_create_collection_member_index.py
> +    fullpaths = tools.fullpaths_populate(args.collectionpath, 3)
With Mark's reorganization, the last argument should be 4.  We should consider an alternative to hardwiring.

2023-08-04 19:01 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        member_lid = str(entry.lid_reference)
Note for myself: take whole LID in the key entry and replace with everything after the bundle LID.

2023-08-04 21:13 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    """Find and store all .xml/.lblx files that contain the filename.
I have changed the term 'filename' to 'keyword'

2023-08-07 17:02 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +            xml_file = xml_file.readlines()
Are you asking if we need to destroy `xml_file` between runs, or if `xml_file.readlines` alters the contents of the `xml_file` variable?

2023-08-07 17:03 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                    line = line.split('=')
See above statement for `xml_file`

2023-08-07 17:06 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        index_root    The lxml root of the data product.
Have replaced with "The root element of the data product's .xml file."

2023-08-07 17:08 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        bundle_root              The root of the bundle.xml file
Have replaced with "The root element of a given bundle.xml file."

2023-08-07 17:13 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +            xml_file = xml_file.readlines()
I think what Matt is saying is that `xml_file` is the open file object, but then you overwrite it with a string, so it's no longer the open file object. This is generally bad form because it is confusing, and if someone tries to use the variable again later it will not have the expected contents. You should use a different variable name for the contents of the file.

2023-08-07 17:14 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                                 the info for the index.
Have replaced with "A list containing all instances of
                                 Bundle_Member_Entry under the given
                                 bundle_root root element."

2023-08-07 17:17 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                                 the info for the index.
Replaced with: The list of all Bundle_Member_Entry elements
                                 within the .xml document. These were located
                                 under a root element found via lxml.objectify

2023-08-07 17:39 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def add_bundle_data(bundle_member_entries, member_index):
They are currently ordered by when each operation generally takes place. I think it would be best to have these ordered alphabetically instead. I will reorder them.

2023-08-07 17:47 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +            xml_file = xml_file.readlines()
Yes, Rob is correct

2023-08-07 17:48 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +                    line = line.split('=')
Here again, my suggestion is that you use a different variable, so that the original form of `line` is available to me for debugging.

2023-08-07 18:09 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def fullpaths_populate(directory, nlevels):
How about `find_all_data_products`, since it also looks for `lblx` files.

2023-08-07 18:16 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                    fullpaths.append(root + '/' + file)
I can change these tools to work with just the shortpaths. Would it be a safe assumption that users would run this code at the top level of a bundle regardless of whether they use the bundle tool or the collection tool?

2023-08-07 18:19 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +                    fullpaths.append(root + '/' + file)
Hmm, this may be a question for @rfrenchseti.  We should not make an assumption about the directory a user is in when they execute the code.  Would it be good practice to change into the directory signified by the input argument?  Or would it be good practice to keep the fullpaths for this purpose, even though they won't go into anything written by the tool?

2023-08-07 18:20 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    """Search the xml file for the LID.
Yes, you are correct

2023-08-07 18:23 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def get_collection_entries(collection_root, namespaces, collection_directory):
I approve, it's short but should make sense to those who will use the tools.

2023-08-07 18:25 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    """Populate the member_index with the collection product information.
Yes, I agree.

2023-08-07 18:26 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    line = line.split('=')
To be more precise, what I think is poor style is to take a variable that is entering a code section with a defined meaning and change it to be a different meaning. For example, in this case `line` is the assigned variable in a `for` loop, but once it leaves this section of code it is a list of entries after various string modifications. Consider that someone might later modify the code as follows:
```
for line in xml_file:
    if 'xmlns:' in line:
        line = ...
    if 'somethingelse' in line: # Expecting line to be the original line from the file
        ...
```
and their code would break unexpectedly. I think it's particularly bad to modify the variable of `for` loop, or the assigned variable of a `with`. I'd think of those as invariants inside the loop.

I don't object too much to:
```
if 'xmlns:' in line:
    line2 = line.replace
    line2 = line2.replace
    line2 = line2.split...
```
even though `line2` changes meaning and type within the code, because there is little chance that someone would come along and insert code in the middle of those lines, and all you're really doing is splitting a large expression across multiple lines so it's easier to read. (Ignoring that `line2` is not a great variable name)

2023-08-07 18:27 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    for root, __, files in os.walk(directory):
A passing comment as I see these emails go by...the standard for "ignore this" is a single underscore, not a double underscore.

2023-08-07 18:34 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +                    fullpaths.append(root + '/' + file)
Okay, that makes sense. 

I still wonder whether perhaps we never need to keep the fullpath as an explicit variable.  We can just use `root + '/' + shortpath` whenever we need it, such as for an input to `os.walk`.  Does that seem correct?

2023-08-07 18:37 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def collection_crossmatch(fullpaths, member_index, directory,
How this escaped me I have no idea. They have now been merged together into `dataprod_crossmatch`

2023-08-07 18:53 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    fullpaths.append(root + '/' + file)
Yes, that would be fine.

2023-08-07 19:24 UTC, matthewtiscareno commented
Another minor comment: We currently use the variable name `root` for two different purposes, namely the root element of an XML file and the root directory specified in the input argument.  We should probably find alternate names for one or both.

2023-08-07 21:03 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    line = line.split('=')
Sure `uri` is fine

2023-08-07 22:31 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                    namespaces.update({line[0]: line[-1]})
According to the PDS Data Standards, we can always expect this format with namespaces and Schematron since they're regulated across all of PDS. See pages 57-59 for examples and further context.

2023-08-07 22:34 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        fullpaths    The list to be populated with filepaths.
I don't see why not.

2023-08-07 23:20 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +                    fullpaths.append(root + '/' + file)
I'm suggesting that shortpaths be the only form of the path that is ever saved in any kind of variable.  If you ever need to use a fullpath (e.g., for `os.walk`), then invoke it using `basedir + '/' + shortpath`

That's my suggestion.  What do you think?

2023-08-11 23:44 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +    """Return the root of the data product .xml file.
It seems that perhaps you have been properly using "root element" to mean the same as my made-up term "structured content," so please change "structured content" back to "root element" here.  The other edits are good.

2023-08-12 00:53 UTC, matthewtiscareno reviewed
I think everything is ready for Python review except some variable name changes. 
- Please change all occurrences of the strings `collectionprod` or `collection_prod` to `collprod`
- All variables that point to a bundle.xml file should use `bunprod` as part of their variable name
- The string `xml` should never appear in a variable name, because it refers to a file's format rather than its function (I apologize for recently losing sight of this principle)

PDS4 nomenclature review:  A `bundle.xml` file (which is both the label of the bundle and the description of its members) is a "bundle product," and I'll embrace Mark's suggestion and go with `bunprod` as an abbreviation for this.  What we usually see as a `collection_*.xml` file is the "collection label."  What we usually see as a `collection_*.csv` file is the "collection product," which we can abbreviate as `collprod`.  Other `*.xml` files are labels for the collection members.

2023-08-12 00:53 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +    for basedir, _, files in os.walk(directory):
What you're calling `basedir` is actually the subdirectory of `directory`, is it not?  Perhaps call it `subdir` instead?

I did mention the idea of `basedir` in my previous review, but I was talking about what you here are calling `directory`.  It's fine to keep that as it is, if you prefer.

2023-08-12 00:53 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +def get_schema(directory, xml_files):
Remembering my previous adage that we should refer to files by their function rather than their format, I think `xml_files` should be renamed.

2023-08-12 00:53 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +              encoding='utf8') as collection_prod_file:
It seems that `collection_prod_file` is the contents of the file whose filename is `collectionprod_file`.  Should we reserve the string `file` for the names of variables that describe a filename?  Whatever we do, it might not be good for two completely different things to have variable names that differ only by an underscore.

2023-08-14 18:35 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    for basedir, _, files in os.walk(directory):
You are correct.

2023-08-14 23:45 UTC, rfrenchseti requested changes
I have not tried to run the programs yet.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        member_index[lid.split(':')[-1]] = temp_dict
Also I don't get these two lines. Is the first one supposed to make a copy of the dictionary? Why? And the second assigns this copy to `member_index[lid]` each time through the loop, overwriting the previous contents each time. Why not just do this once after the loop is over?

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    """Match the LID of a file to its counterpart in the dictionary.
counterpart in the member_index
But what does it do once it matches it?

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    for path in label_paths_sorted:
It's fine to just say `for path in sorted(label_paths)` if you want.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        ),
I think this needs to be indented

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +            remove_blank_text=True))
No reason to split the lines here

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +def file_creator(directory, keyword, member_index):
`file_creator` sounds like an object. If you're creating something, make it a verb, like `create_results_file`.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    labels = list(member_index[_].keys())
Eek! Underscore is supposed to mean "variable we are ignoring". Don't ever use it as an actual variable name!

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    """find and return all instances of Bundle_Member_Entry.
Capitalize Find

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        bundle_member_entries    A list containing all instances of
Generally speaking, you don't need to name the return value, since that internal name is invisible to the user. Just describe it.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    """Find and store all .xml/.lblx files whose filenames contain the keyword.
What do you mean by "store"? It looks like it just returns a list.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                             exception is raised.
If you really want to return an exception instead of just an empty list, you should name which exception you raise.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    if keyword in file:
If this function does what I think it does, you're going to want `keyword` to actually be a regular expression so the user has better control over what filenames to match.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    if not files_found:
See earlier comments on this exception and error message.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                  'cassini': 'http://pds.nasa.gov/pds4/mission/cassini/v1'}
Why is `cassini` always in the namespaces returned? Certainly not all bundles are related to Cassini.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    namespaces.update({uri[0]: uri[-1]})
Just say `namespaces[uri[0]] = uri[-1]`

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    """Shorten the paths in the member_index dictionary.
This function does not use the `member_index` dictionary in any way.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +
Remove extra blank line.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
>  parser = argparse.ArgumentParser()
Parsing of arguments should be inside the `main`. You don't want it to try to parse arguments if you just import this module. Same in other top-level programs.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
I don't see where `directorypath` is added as a possible argument.

Should use `os.sep` instead of `/`.

I don't understand this anyway...isn't the bundle name the last element of the directory path, not the second-to-last?

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
Say where the magic number 3 comes from

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +def get_schema(directory, label_files):
Should this be something like `get_namespaces`? Right now it implies it is returning a single schema, not a list of URLs to schemas.

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    dataprod_paths = tools.find_all_data_products(args.directorypath, 2,
Another magic constant, 2

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundleset_member_index.py
> +        args.directorypath, 2, 'bundle', bundleset_name)
See earlier comments

2023-08-14 23:45 UTC, rfrenchseti commented on indextools/pds4_create_collection_member_index.py
> +    collection_name = args.collectionpath.split('/')[-2]
See earlier comments

2023-08-21 17:10 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                        use '_'
I've confirmed that this replacement does not negatively affect the functionality of the code.

2023-08-21 17:11 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +            temp_dict.update({label: '_'})
This has been replaced with `None`

2023-08-21 17:16 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        ),
This has been fixed due to the character limit extension.

2023-08-21 17:23 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    labels = list(member_index[_].keys())
It has been changed to a true variable name `found_keys`

2023-08-21 17:25 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    """Find and store all .xml/.lblx files whose filenames contain the keyword.
I have changed "store" to "return"

2023-08-21 17:54 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                  'cassini': 'http://pds.nasa.gov/pds4/mission/cassini/v1'}
The inclusion of `cassini` is from initial development of these tools. It can be removed without affecting any current results. 

`pds` is a different story. Currently the `get_schema` code is pulling the schema from this specific portion of the bundle.xml file (this is from `cassini_vims_cruise`):
```
...
  xmlns="http://pds.nasa.gov/pds4/pds/v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:geom="http://pds.nasa.gov/pds4/geom/v1"
  xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 https://pds.nasa.gov/pds4/pds/v1/
...
```

While `pds` is represented here, it is not explicitly named, and therefore can't be easily attributed to a `pds` key within the `namespaces` dictionary.

@matthewtiscareno  would it be safe to assume that `xmlns="http://pds.nasa.gov/pds4/pds/v1"` represents the `pds` namespace?

2023-08-21 17:58 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    """Shorten the paths in the member_index dictionary.
This statement was left over from when `shortpaths` had a different application within the library.

2023-08-21 18:21 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
`/` has been replaced with `os.sep`

Can you clarify your statement about `directorypath`?

2023-08-21 18:40 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
I don't see how this program can run at all. When you define the arguments with ArgumentParser() you never add `directorypath` as a possible argument. You do in other top-level programs, just not this one. So I would expect this program to crash as soon as it's run.

Also, I don't understand the purpose of the split. What directory are you expecting the user to provide? If the directory is the bundle itself, like:

```pds4/bundles/uranus_occs_earthbased/uranus_occ_u0201_palomar_508cm```

then shouldn't you be taking the last directory name, not the second-to-last?

2023-08-21 19:13 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                            '__',
It has been replaced with `None`

2023-08-21 19:22 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def add_collection_data(directory, collprod_path, member_index):
The order of arguments is determined by when they are first mentioned within the function itself.

While there is no requirement for how these arguments should be ordered, I can change that. But I don't mind it.

2023-08-21 19:35 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +def add_collection_data(directory, collprod_path, member_index):
Think like an outside user calling the function. The order of the arguments should make some kind of sense, if possible. At that very least it should be consistent within a single API. The fact that they are used inside the function in this order is not relevant to the user. This is just a general concept, not just relevant here. When you have different functions take the same arguments in different orders, you have a higher chance of people passing in the wrong values.

2023-08-21 19:37 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
No, you can't assume that a directory path ends with a /. In fact it is not at all normal for it to do so. If you really want to include the possibility of a trailing slash, then do `strip(os.sep)` before you do the split, then take the last directory name. That will handle both possibilit.es

2023-08-21 19:38 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
Actually it's worse than that...just because you're on Windows doesn't mean someone will pass in a path using backslashes. They can also use forward slashes and Python will still handle it fine. Maybe do `strip(os.sep).strip('/')` to cover all possibilities.

2023-08-21 19:52 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
To clarify, did you mean `strip(os.sep).split('/')`? The original replacement just returns the whole string.

2023-08-21 19:56 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
I mean

```
bundle_name = args.directorypath.strip(os.sep).strip('/').split('/')[-1]
```

The point is if the user does supply a trailing / or \, remove it, then do the split. That way the behavior of the split is predictable.

But really, now that I know you're just looking for the final path element, wouldn't it be better just to use `os.path.split` and forget about all this?

2023-08-21 20:03 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
Something like `basedir, bundle_name = os.path.split(x)`?

2023-08-21 20:05 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundle_name = args.directorypath.split('/')[-2]
`basedir, bundle_name = os.path.split(args.directorypath)` yes

2023-08-21 21:46 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        if subdir.count(os.sep) - directory.count(os.sep) < nlevels:
Here is the proposed solution (variable names subject to change):

```
for basedir, subdirs, files in os.walk(base_directory, topdown=True):
    for file in files:
        if keyword in file:
            if file.endswith(('.xml', '.lblx')):
                files_found.append(os.path.join(basedir, file))
                subdirs[:] = []
end = time.time()
```

This grabs the first instance of a match, then sets the value of `subdirs[:]` to `[]`. By assigning an empty list to subdirs[:], it effectively stops the recursion into subdirectories at this point in the directory tree traversal. Then, due to `topdown=True`, it starts back at the top. 

According to rudimentary `time.time()` usage, this method is ~8-10x faster than the currently implemented version. The only problem is that it will catch the first instance of a match, then move on. It can be said that only one `bundle.xml` or related label file can exist at one time, so it shouldn't be an issue (at least for `get_member_filepaths`)

I have tested this in an isolated environment. It catches the intended files, and also works with the `uranus_occs_earthbased` bundleset with multiple instances of `bundle.xml`.

2023-08-21 22:39 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if subdir.count(os.sep) - directory.count(os.sep) < nlevels:
Yes, that looks like a good solution. It does handle the case of multiple .xml files in the same directory, just not the case where there are also such files in subdirectories (which is the whole point of pruning the tree anyway).

2023-08-22 06:01 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +        raise FilepathsNotFound('No files ending in ".xml" or ".lblx" could '
The real problem needing an error to be raised would be if a bundle member or collection member is left without a corresponding path.  Emilie, would you agree?

2023-08-22 06:06 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +                    if keyword in file:
Emilie and I discussed this a bit today.  I was wondering whether she should look to translator.py in the pds-webtools repo as a model (and maybe even a source of functions) for dealing with regexes, or whether that is too complex a tool for the need here.

2023-08-22 17:27 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        raise FilepathsNotFound('No files ending in ".xml" or ".lblx" could '
That seems reasonable. However, if you ever raise an exception, you need to catch it somewhere up the chain and do something reasonable with it, like print an error message - don't just let the program crash.

2023-08-22 17:28 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +                  'cassini': 'http://pds.nasa.gov/pds4/mission/cassini/v1'}
Yes.  The string `xmlns="` can be taken to signify the primary PDS namespace, while `xmlns:foo="` signifies the `foo` namespace.

2023-08-22 17:29 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    if keyword in file:
That doesn't seem like the right solution to me. The whole point of translator.py is to take a string described by one regex and translate it into another string with some of the field substituted. That is not what we're trying to do here. The Python `re` module has all of the functionality you could want for this task. You just want the user to be able to specify a regex on the command line, and then use some version of `re.match` to see if the filename matches the regex. Ideally the user could specify more than one regex, and you would loop through them and try them all; if any one matches, then you include that file.

2023-08-22 17:33 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
It comes from an assumption of how many levels there are between the base directory and what you're looking for.  This number is not defined by the specification and can be different depending on how holdings are implemented, so we need to be careful.

2023-08-22 17:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
Perhaps this needs to be a command line option then?

2023-08-22 17:53 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
It would eliminate the reliance on hardcoded numbers. Plus, introducing a new argument wouldn't be difficult at all.

2023-08-22 19:05 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
I think an argument with a default value might be best.

2023-08-22 19:17 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    if keyword in file:
The whole point is that when creating our custom index files for a bundle for OPUS import, we may only want to include certain files in the index. For example, with the Uranus occultations, there are files:
```
u13_sso_390cm_2200nm_radius_alpha_egress_100m.xml
u13_sso_390cm_2200nm_radius_alpha_egress_500m.xml
u13_sso_390cm_2200nm_radius_alpha_egress_1000m.xml
```
But since these all map to the same OPUS ID, we might choose to only include one of these in the index file so that OPUS import works more easily. Thus we need to be able to specify a regex that chooses only the proper resolution when building the index file. Since we want to be able to include multiple XML files from multiple locations (e.g. both rings and atmospheric occultations) we need to be able to specify multiple regex.

2023-08-22 19:20 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                    if keyword in file:
There's no point in hard-wiring a regex...in that case you just don't need a regex at all for simple searches for `.xml` and `.lblx`. The idea is that each bundle/bundleset needs its own rules, and those would most easily be specified on the command line.

2023-08-22 22:33 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
So, for example, if we had a command line option for `--bundle` or `--collection`, it would default to 3, but if it were `--bundleset`, it would default to 2? Is that a correct interpretation?

2023-08-22 22:37 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        raise FilepathsNotFound('No files ending in ".xml" or ".lblx" could '
Would a `sys.exit(1)` be applicable here?

2023-08-22 22:40 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        raise FilepathsNotFound('No files ending in ".xml" or ".lblx" could '
This is supposed to be a general library, right? I think it's bad form for a library function to exit the program without giving the calling routine a chance to deal with the error in some other way. This is exactly what exceptions were designed for. You just have to catch the exception in the top-level programs and do something intelligent with it - like print an error and exit there.

2023-08-23 00:15 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
Not necessarily.  Notice the difference between the following:
https://pds-rings.seti.org/pds4/bundles/cassini_iss_saturn/data_raw/14547xxxxx
https://staging.pds.seti.org/pds4/bundles/cassini_iss_saturn/data_raw/145xxxxxxx/14547xxxxx

2023-09-01 18:00 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
After a productive discussion with Rob yesterday, here is the solution I landed on:

```
def get_member_files(directory, nlevels, keyword, subdirectory):
    file_paths = []
    regex = re.escape(keyword)+r'\w*\.(xml|lblx)'
    base_directory = os.path.abspath(x)
    for subdir, _, files in os.walk(base_directory):
        if nlevels is not None:
            if subdir.count(os.sep) - base_directory.count(os.sep) < nlevels:
                for file in files:
                    if re.match(regex, file):
                        file_paths.append(tools.shortpaths(
                            os.path.join(subdir, file),
                            directory,
                            directory[directory.find(subdirectory):])
                        )
        else:
            for file in files:
                if file.endswith(('.xml', '.lblx')):
                    file_paths.append(tools.shortpaths(
                        os.path.join(subdir, file),
                        directory,
                        directory[directory.find(subdirectory):])
                    )
                    
    return file_paths
  ```

This function will replace the functionality of `get_member_filepaths` and `find_all_data_products`. Some key points to notice are:
- There is now a regex that captures collection_*.xml and bundle.xml files. it is only in the lines of code that are used when it is looking for toplevel label files.
- nlevels has been re-introduced, and now determines what functionality is used. If nlevels=2, the code will return the toplevel label file for the bundle/collection/bundles in a bundleset. If nlevels is set to `None`, it will look for all data products within the directory tree.

2023-09-01 19:05 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        args.directorypath, 3, 'bundle', bundle_name)
I suggest something like this as a minor improvement. Let the regex guide things all the time, and reduce the redundancy. (I didn't try to make the indents perfect or test it)

```
def get_member_files(directory, nlevels, subdirectory, regex=r'\w+\.(xml|lblx)'):
    file_paths = []
    base_directory = os.path.abspath(x)  # I'm not sure what x is supposed to be
    base_dir_sep = base_directory.count(os.sep)
    for subdir, _, files in os.walk(base_directory):
        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
                for file in files:
                    if re.match(regex, file):
                        file_paths.append(tools.shortpaths(
                            os.path.join(subdir, file),
                            directory,
                            directory[directory.find(subdirectory):])
                        )
                    
    return file_paths
```

2023-09-05 17:17 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                    if keyword in file:
This is now addressed with a new regex expression in `get_memebr_filepaths`

2023-09-06 16:58 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    """Create the empty index with correct labels and contents.
This has been addressed with the rest of the comments asking for better documentation for all the functions.

2023-09-06 17:01 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def add_collection_data(directory, collprod_path, member_index):
`member_index` has been moved to the end of the list of arguments for all functions.

2023-09-06 17:04 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        member_index[lid.split(':')[-1]] = temp_dict
Both of these comments have been addressed.

2023-09-15 19:16 UTC, rfrenchseti requested changes

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    The file is opened within the base_directory and contains the keyword in the name.
I'm not sure what it means that the file "contains the keyword in the name". Is there something else in the name? Is it really a keyword or are you just passing in the name of the file?

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    found_keys = list(member_index.keys())[0]
What happens if `member_index` is empty?

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    Each path within label_paths parsed and scraped for its LID. If this LID exists as an
IS parsed

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    entry in member_index, the path is attributed as a value to the 'Path' key. If it has
"is attributed as a value to" is kind of wordy and vague. How about just "the 'Path' key is set to this value".

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +            print(f'PDS4 label found but not a member of this collection: {path}, {lid}')
"this collection" - will the user know what collection is being talked about?

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        root = (objectify.parse(os.path.join(base_directory.replace(subdirectory, ''),
If `base_directory` is the root of the bundle, then it doesn't include the `subdirectory` name, does it? In which case this replace does nothing. However, you have to be careful about generic replaces in paths. What happens if some part of the path just happens to contain the name of the "subdirectory" in it? For example, if `base_directory` is `/home/esimpson/my_bundles/data_raw/other_data/something_else/cassini_iss` and `subdirectory` is `data_raw` then your replace is going to mess up the path.

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +def get_bundle_entries(bunprod_root, namespaces):
I would find this easier to read if it were called `get_bundle_member_entries`

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    try:
Try to minimize the number of lines of code inside a try/except. Which of these lines do you expect to raise the IndexError? Also does printing this error give the user enough information? Do they know what collection, what file, etc has the problem?

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +# FIXIT
Does this still need to be fixed?

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    shortpath = fullpath.replace(base_directory, replacement_text)
See earlier comment about the danger of using replace on a full path. There should be a safer way to do this.

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +def get_member_files(directory, nlevels, subdirectory, file_type):
I thought we were going to change this function to take in the regex directly? That way the caller can limit the specific names of the files being searched for, not just the suffix. Also there is no longer a "keyword". The comment paragraph below refers to old code.

2023-09-15 19:16 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
Don't you still have to cut off the recursion for lower subdirectories if we've reached the desired depth?

2023-09-25 19:24 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +# FIXIT
No, this has been fixed.

2023-09-25 19:45 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +            print(f'PDS4 label found but not a member of this collection: {path}, {lid}')
They should, considering that they have to specify the directory to the collection itself as the command line argument.

2023-09-26 18:38 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        try:
All exceptions have been replaced with printed messages

2023-09-26 22:43 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    The file is opened within the base_directory and contains the keyword in the name.
In the case of bundle.xml files, no. In the case of collection_*.xml files, there is expected extra words. If the user wanted to, they could even use an entirely different keyword to suit the naming schema of their label files.

2023-09-26 22:51 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        root = (objectify.parse(os.path.join(base_directory.replace(subdirectory, ''),
I have changed it to use basedir instead, which eliminates the need for the `replace`

2023-09-26 23:02 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    try:
Rewrote the try/except to be shorter, and added more info to the error message.

2023-09-29 16:35 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    namespaces = {'pds': 'http://pds.nasa.gov/pds4/pds/v1'}
I rewrote the `get_namespaces` function. It now works as intended.

2023-09-29 17:55 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +def get_member_files(directory, nlevels, subdirectory, file_type):
This has now been fixed to take the regex directly.

2023-09-29 19:01 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
To my knowledge, this does. We can discuss this when you are back.

2023-09-29 19:13 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +    found_keys = list(member_index.keys())[0]
I have put in an extra warning to check if member_index does not populate.

2023-10-06 11:44 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +            print(f'PDS4 label found but not a member of this collection: {path}, {lid}')
But this is a utility library. There is no "command line argument". You have no idea where the caller got its information from. It's always better to be as explicit as possible in error messages.

2023-10-06 11:47 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    The file is opened within the base_directory and contains the keyword in the name.
But this is for creating an output file, right? You are using the keyword to create the name of a CSV file. So in the documentation, you should say what the name of the output file will be. In this case it looks like it's <keyword>_member_index.csv. Just saying it's "in the name" doesn't tell the person calling this function what the name actually is.

2023-10-06 11:49 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
As written this code will ignore too-deep directories from your regex match, but you still allow os.walk to walk down the entire tree no matter how deep it is. Previously you had written code that replaced the subdirs return value (the one currently marked with _) with the empty list to prevent os.walk from recursing further down the directory structure. That should be done here to improve performance.

2023-10-12 17:24 UTC, rfrenchseti requested changes
This code is starting to look really nice. It's concise but readable, well documented, makes logical sense, and efficient. I only have minor comments at this point.

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    regex = r'[\w-]+\.(?:'+re.escape(args.filesuffix)+')'
Is the file you're looking for always called exactly `bundle.xml`? If so, all of this searching is overkill. You could just look directly if the file `{directorypath}/bundle.xml` exists and skip the regex and `get_member_files`. Also you wouldn't need the suffix command line argument.

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    # Here we are using 2 for the nlevels parameter to specify that only the files in
This is certainly true, but I think it's missing the WHY. The thing to describe here is that you expect the bundle member entries to only exist within the top two directory levels, and the program won't work if that assumption doesn't hold.

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_create_bundleset_member_index.py
> +    regex = r'[\w-]+\.(?:'+re.escape(args.filesuffix)+')'
Now for this one, we're looking at multiple directories so you do have to do the directory search. However, are you always looking for `bundle.xml`? If so, 1) you don't need the suffix command line argument and 2) the regex could actually explicitly say `bundle.xml` instead of `*.xml`, thus guaranteeing you only find the file you care about.

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_create_bundleset_member_index.py
> +    # In get_member_files, nlevels is set to 2 here to limit the search to the
This is a good WHY explanation.

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                                                  namespaces=namespaces)
Bad indent

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +                          If nlevels = 2, the search returns the toplevel label file.
Isn't this nlevels=1?

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    This function will return the first instance of an .xml/lblx file that exists within
Instead of saying "of an .xml/lblx file" it should say "of a file that matches the given regex"

2023-10-12 17:24 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    Inputs:
Add blank line

2023-10-13 18:41 UTC, esimpsons3ti commented on indextools/pds4_create_bundleset_member_index.py
> +    regex = r'[\w-]+\.(?:'+re.escape(args.filesuffix)+')'
No. This regex is also used to find the `collection_*.xml` files. If `bundle` is in the regex, then it would only work with `bundle.xml` files.

2023-10-13 18:42 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    regex = r'[\w-]+\.(?:'+re.escape(args.filesuffix)+')'
No, the regex also catches `collection_*.xml` files.

2023-10-13 19:40 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +                          If nlevels = 2, the search returns the toplevel label file.
It is, except in the case of bundlesets. I am going to change the wording to better reflect the intended behavior.

2023-10-13 20:55 UTC, esimpsons3ti commented on indextools/pds4_create_bundleset_member_index.py
> +    regex = r'[\w-]+\.(?:'+re.escape(args.filesuffix)+')'
I rescind this comment now that I know what you were talking about.

2023-10-13 20:56 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    regex = r'[\w-]+\.(?:'+re.escape(args.filesuffix)+')'
I rescind this comment and will apply the suggested changes.

2023-10-13 23:05 UTC, esimpsons3ti commented
I will finish these changes once I hear back from @matthewtiscareno

2023-10-16 21:53 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
Would it be advisable to disable Windows use? Ideally these tools can be used by anyone. In this case, is it better to be exclusive than to be unreliable?

2023-10-16 21:56 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
That's a good question for Matt. Mitch was a Windows user, but I don't know many other PDS people who are. Alternatively you can just fix it to work on Windows, but you have no easy way of testing it.

2023-10-16 22:08 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
Wouldn't this problem be fixed if you did the following instead?
```
>>> for x, y, z in os.walk('j:'+os.sep+'Temp'):
...     print(x)

```
Emilie doesn't really have a good way to test whether everything works on Windows, and I agree that we shouldn't spend much time on Windows compatibility.  But it might seem to be good practice to habitually write things with this sort of generality.  Or perhaps I'm missing the point.

2023-10-16 22:12 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
The issue is that `J:\Temp` is from the command line. Because Python supports either Windows or Unix filename separators on Windows, a user can say either:
```
python program.py J:\Temp
python program.py J:/Temp
```
and the code has to deal with both. The easiest thing to do usually it do replace('\\', '/') in all directory paths you're given and just use the Unix format. We do this in a lot of our code, such as PdsFile. If you ever use `os.path.join` you get backslashes again, so we always do the replace on the result of that join. Often we write a function called `clean_join` that just does this for you all the time. You also want any CSV files you create to only have forward slashes in them, which is something else we've discussed about Emilie's code.

2023-10-16 22:39 UTC, matthewtiscareno commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
That all seems reasonable.  And you all do this for PdsFile even though you don't have any Windows users on the team, so none likely to use the software in the foreseeable future, correct?  Why wouldn't we do the same here?

2023-10-16 22:41 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
Actually, we do. Debby is a Windows user, and PdsFile is part of OPUS, so it's important. Whether you support Windows here is up to you. I think it's probably a good idea to do so. It's just a matter of teaching Emilie what that implies throughout the code.

2023-10-16 23:14 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
This is what I've gathered:
- Ensure that all paths that are fed into the functions are Unix format by replacing '\' with '/'
- ensure that all paths that are created via `os.path.join` are made to be Unix format via `clean_join` or `replace`

This isn't too much hassle, I think. Making these tools available for Windows users is important for the accessibility of the service it provides.

2023-10-16 23:20 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
Since you're writing a library and don't know where the arguments are coming from, you could clean up the directory names inside each function. Just make some utility function called `clean_directory_name` or something that does the replace of `\` with `/`. You could also have a `clean_join` if you want. Here's an example:
```
def clean_join(path, *paths):
    return os.path.join(path, *paths).replace('\\', '/')
```

2023-10-17 19:05 UTC, esimpsons3ti commented on indextools/pds4_index_tools.py
> +        if nlevels is None or subdir.count(os.sep) - base_dir_sep < nlevels:
I have introduced two new functions that address the changes above.

2023-10-17 22:59 UTC, rfrenchseti commented on indextools/pds4_index_tools.py
> +    found_keys = list(member_index.keys())[0]
This is another case of a library function exiting the program. I don't think this should ever happen. It should raise an exception and let the caller deal with it. Perhaps the caller wants to do something other than exit...  You could just convert this to a ValueError exception using the same error message.

2023-10-17 23:00 UTC, rfrenchseti approved these changes
Except for my one comment about needing to change an exit into an exception, I think the rest is good enough to continue development on new top-level programs.

2023-12-05 18:27 UTC, merged