Adding new indexing tool for review
SETI/rms-data-projects pull request #58
Opened 2023-12-06 19:02 UTC by esimpsons3ti

Here is the singular indexing tool. Here are some notes for using it:

There are two required parameters for the command: The directory path, and the `glob` pattern.
- The directory path should end where you want the final index file to be placed. The glob pattern should start from the next subdirectory from the directory path. For example:

```
python3 indexing_tool.py /Volumes/Emilie-Data/pds4-holdings/bundles/ "uranus_occs_earthbased/uranus_occ_*/data/rings" --filesuffix "100m.xml"  --elements-file "elements.txt" --xpath
```

This does the following:
- Finds all files ending with "100m.xml"
- Only scrapes the text from elements matching the contents of elements.txt (an example is included in this pull)
- Converts the headers to XPaths
- Drops the resulting index file in `/Volumes/Emilie-Data/pds4-holdings/bundles/`

NOTE: If you know that duplicate element tags will be present in the final product (version_id, for example), use the --xpath command to show where each instance of the element's value comes from.

2023-12-18 18:45 UTC, rfrenchseti submitted a review, later dismissed
- Nicely done. This looks like well-documented, clean, Pythonic code.
- My comments are minor and you can take or leave many of them as you wish.
- However, one big one: right now the output file is put in the same directory hierarchy as the bundle, but this won't always be possible. Normally the bundle is on a filesystem that is mounted read-only, so you can't write the index file there. You need something like an `--output-file` argument to specify the full path and filename of the resulting file.

Sorry this took so long to get to.

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +Dependencies:
I wouldn't put these here. Just put them in a `requirements.txt` file, since they will need to be installed with "pip install" anyway. If you put them in two places they will just get out of sync.

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +
Just a personal preference, I wouldn't put blank lines between these (and everywhere else in this file). The whitespace just makes it look like they aren't grouped together.

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +        for space in list(prefixes.keys()):
Do you actually need the `list` here? I would've thought `keys` returns an iterable.

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +        for space in list(prefixes.keys()):
Ditto

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +        for space in list(prefixes.keys()):
Also I'm not clear what `space` means. Is this a "namespace"? If so might just call it that, since space is a character.

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +    if elements_to_scrape is None or any(tag.endswith("}" + elem) for elem in
Just a minor suggestion. I would format this as either:

```
    if elements_to_scrape is None or any(tag.endswith("}" + elem)
                                         for elem in elements_to_scrape):
```

or

```
    if (elements_to_scrape is None or 
        any(tag.endswith("}" + elem) for elem in elements_to_scrape)):
```

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +            'pds:bundl': bundl
This is really `bundl` without an e?

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +        [col for col in df.columns if col not in [
I would put the `if` on the next line instead of splitting the list

2023-12-18 18:45 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +    columns_order = ['LID', 'pds:fname', 'pds:spec', 'pds:blid', 'pds:bundl'] + \
We generally try to avoid using `\` line terminators, although this isn't a bad use for one. You could also initialize the list here and say `columns_order += ...` on the next line, or you could wrap the whole thing in parentheses.

2023-12-18 18:49 UTC, esimpsons3ti commented on indextools/indexing_tool.py
> +            'pds:bundl': bundl
The naming came from the original .tab document you sent me a while ago, `uranus_occultations_index.tab`. I just replicated the naming to be consistent with this document. It can be changed to be `bundle`, if you prefer.

2023-12-18 18:57 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +            'pds:bundl': bundl
Oh, I see. There are a few weird things in that file. Like that they use Windows-style `\` in `pds:spec`. We don't need to echo that file so precisely if what they do doesn't make sense. Let's go for `bundle`.

2023-12-18 19:27 UTC, esimpsons3ti commented on indextools/indexing_tool.py
> +    parser.add_argument('--nlevels', type=int,
I have removed the statement.

2023-12-18 19:48 UTC, esimpsons3ti commented on indextools/indexing_tool.py
> +            prefixes = {v: k for k, v in namespaces.items()}
It unfortunately doesn't. I essentially needed `namespaces` but with the keys and values reversed.

2023-12-18 20:00 UTC, esimpsons3ti commented on indextools/indexing_tool.py
> +        for space in list(prefixes.keys()):
The `list` here was left over from development. It has been removed.

`space` has been renamed `namespace`

2023-12-18 23:23 UTC, rfrenchseti requested changes

2023-12-21 21:11 UTC, rfrenchseti requested changes
- The file is called `indexing_tool.py` but the Usage message in the file calls it `xml_bundle_scraper.py`. I don't think either is a great name. How about something like `pds4_create_xml_index,py`?

2023-12-21 21:11 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +    if args.output_file:
For each of these you set `output_path` but then don't use it. I think you should set it to the correct value (it's wrong for the else clause) and then just do a single call to `write_results_to_csv` after the `if`.

2023-12-21 21:11 UTC, rfrenchseti commented on indextools/indexing_tool.py
> +    parser.add_argument('directorypath', type=str,
From the code below it seems like `directorypath` should be a glob pattern but that isn't mentioned here.

2024-01-05 19:58 UTC, rfrenchseti requested changes
Two feature requests:

1) Provide some way to sort the output lines. Right now they are in whatever order glob returns. I would rather have them sorted, for example, by filename, to group the "rings" and "global" files together for the Uranus occs. So we could have a new command line argument `--sort-by` like:

```
---sort-by pds:filename
```

A more extreme example would allow multiple fields and sort on them in order:

```
--sort-by pds:bundle_lid pds_filename
```

Since you're already using pandas to write the CSV file, you could also use pandas to do the sorting for you.

2) This one is weird, but I use software to manipulate CSV files that doesn't like having special characters like ":" or "/" in headers. It would be nice to have an option like `--clean-header-field-names` that would replace ":" and "/" with "_" or something similar.

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/elements.txt
> +logical_identifier
If this file is going to stay here, it should probably be renamed `sample_elements.txt` to avoid the confusion of thinking it's some kind of master elements file.

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +import re
re is no longer used

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +        [--nlevels NLEVELS]
nlevels is no longer used and should be removed everywhere

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +        [--file-suffix FILE_SUFFIX]
file-suffix is no longer used and should be removed everywhere

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    python3 indexing_tool.py /path/to/top/level/directory
This seems too complicated. How about just:
```
python3 pds4_create_xml_index.py <toplevel_directory> "glob_path1" "glob_path2" --output_file <outputfile> --elements-file sample_elements.txt --verbose
```

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +        xpath_final    Converted XPath expression.
I think there's no reason to "name" the return value. Just say:
```
Returns:
    Converted XPath expression.
```
here and everywhere else.

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +def store_element_text(element, tree, results_dict, prefixes):
prefixes is not used

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +        tag = str(element.tag)
tag is not used

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +            'pds:blid': blid,
Looking at the CSV file, I couldn't figure out what a "blid" is. Is that a "bundle LID"? If so maybe name the field `pds:bundle_lid` to make it clearer?

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                     'pds:blid', 'pds:bundle'])
Align list with elements above

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                        help='The path to the directory containing the bundle '
bundleset, bundle, or collection

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                        help='Optional text file containing elements to scrape')
If not specified, all elements found in the XML files are included.

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                        help='A flag that will activate XPath headers in the final '
If specified, use full XPaths in the column headers. If not specified, use only (something here)

2024-01-05 19:58 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                        help='A flag that will activate printed statements throughout '
You don't have to say "A flag that will". Just say "Activate..."

Better yet just say something like "Turn on verbose mode and show the details of file scraping"

2024-01-05 21:33 UTC, esimpsons3ti commented
Oops, that was a premature request for review @rfrenchseti . I still need to implement the features you want.

2024-01-05 23:15 UTC, esimpsons3ti commented
I have now implemented the requested features. Please review at your convenience

2024-01-05 23:42 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                        help='A flag that will activate XPath headers in the final '
I would still get rid of the "A flag that will...". In fact just kill the whole sentence. Just need to say "If specified, use full XPaths..."

2024-01-05 23:46 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +                         Replace the ":" and "/" with Windows-friendly characters.
Actually this has nothing to do with Windows. The idea is to turn headers into something that would be a legal variable name - so "." doesn't work either. Maybe you could turn ":" into "_" and "/" into "__".

2024-01-05 23:49 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +            ':', '_').replace('/', '.'), inplace=True)
Seems like the blank lines in this area are inconsistent.

2024-01-06 00:00 UTC, esimpsons3ti commented on indextools/pds4_create_xml_index.py
> +            ':', '_').replace('/', '.'), inplace=True)
This odd spacing is due to the autopep8 feature on VSCode, which applies on save. I will disable it for now, since I don't agree with a few of these spacings

2024-01-06 00:16 UTC, rfrenchseti approved these changes
Works great.

2024-01-13 00:18 UTC, matthewtiscareno reviewed
This is very good!  I have only a few small comments, which all have to do with helping readers like me to understand the code, not with actual functionality.

2024-01-17 00:23 UTC, matthewtiscareno approved these changes

2024-01-17 00:24 UTC, matthewtiscareno commented
Looks great now.  Thanks.

2024-01-18 21:36 UTC, merged