New feature dealing with `nil` values.
SETI/rms-data-projects pull request #74
Opened 2024-02-26 23:01 UTC by esimpsons3ti

This new code now scans for the allowed nillable values in the associated data dictionaries and replaces nilled elements in data products with their respective "default" values. Also included is a new config file.

Fixes #69

2024-02-27 19:03 UTC, rfrenchseti requested changes

2024-02-27 19:03 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    config = load_config_file(config, 'pds4indextools.ini')
This is going to need to be more sophisticated. It needs to work if the user runs the program from another directory, since this will be an installed module. The way it's written right now, it will look for the default config file in the *current* directory, not the directory where this module lives.

```
$ mkdir test_dir
$ cat > test_dir/t.py
import os
print(os.getcwd())
$ python3 test_dir/t.py
/home/rfrench      <<<<=== This is the current directory, not where t.py lives
$ cat > test_dir/t2.py
import os
print(os.path.realpath(__file__))
$ python3 test_dir/t2.py
/home/rfrench/test_dir/t2.py    <<<<=== This is where the module lives
```

So you need to do something like the last example, then strip off the directory name and append `pds4indextools.ini` to it before reading.

2024-02-27 19:03 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +def parse_xsd_file(xsd_file, nillable_elements_info):
This does more than just parse the xsd file. It also updates the `nillable_elements_info dictionary`. How about something like `update_nillable_elements_from_xsd_file`.

2024-02-27 19:56 UTC, esimpsons3ti commented on indextools/pds4_create_xml_index.py
> +                                        f'//xs:complexType[@name="{type_name}"]')
I have cleaned up the code and the indents.

2024-03-01 01:42 UTC, matthewtiscareno approved these changes
I have one minor comment.  Otherwise this all looks great.  

I'll go ahead and approve, and @esimpsons3ti and @rfrenchseti can determine how to resolve my minor comment.

2024-03-01 01:42 UTC, matthewtiscareno commented on indextools/pds4_create_xml_index.py
> +                url, nillable_elements_info)
Is it good practice for `nillable_elements_info` to be both an argument and the returned value?

2024-03-01 17:31 UTC, esimpsons3ti commented on indextools/pds4_create_xml_index.py
> +                url, nillable_elements_info)
I have seen it done in numerous applications, and it is considered acceptable as a general practice in Python. Although I'm wondering if it should be just `update_nillable_elements_from_xsd_file(url, nillable_elements_info)`

2024-03-01 17:38 UTC, pds-admin commented on indextools/pds4_create_xml_index.py
> +                url, nillable_elements_info)
Yes, I was going to make that exact comment. It's perfectly fine to use the same variable as argument and return because in this case what we're doing is updating the same variable over and over again. It's no different than saying something like `x=x+1`. It wouldn't make any sense to use a different variable name. But in this particular case, the function is actually mutating the argument, so it probably shouldn't be returning anything at all.

2024-03-01 17:45 UTC, esimpsons3ti commented on indextools/pds4_create_xml_index.py
> +                url, nillable_elements_info)
I'll change the function and all of it's calls to reflect this.

2024-03-01 18:13 UTC, rfrenchseti requested changes

2024-03-01 18:13 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    """Convert strings to correct data types.
This comment doesn't agree with the function name.

2024-03-01 18:13 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    """Loads the default .ini configuration file and updates the existing config object.
If this loads the default file and the user file, then there's no reason to pass in a config parameter for updating. Just let this function create the config object. Also the user file is being read a second time at line 390.

2024-03-01 18:13 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +        config: The configuration data.
Different format for parameters than other comments

2024-03-01 18:13 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +            f'No files matching {pattern} found in directory: {directory_path}')
This doesn't seem like it needs to be on a separate line

2024-03-01 18:43 UTC, esimpsons3ti commented on indextools/pds4_create_xml_index.py
> +    """Convert strings to correct data types.
All values a `configparser` object can return are strings. In the instance of a value representing an `int` or a `float`, they need to be converted to their correct data types. So I agree with the comment, but not the function name. How about `convert_default_data_type` or something similar?

2024-03-01 18:53 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    """Convert strings to correct data types.
So there's what the function does internally, and what the *purpose* of the function is. Yes, internally the function converts some strings (specifically config object strings, which is not what the comment really says) to a specific data type. But is that what the person calling the function cares about? I would think they care that it returns the default nil value. They don't know or care how this happens. So I like the function name personally. If you want to describe why this process is necessary, feel free to add another comment - but not in the function docstring, which is user-centric.

2024-03-01 19:04 UTC, esimpsons3ti commented on indextools/pds4_create_xml_index.py
> +            f'No files matching {pattern} found in directory: {directory_path}')
Something I missed from the autopep8 tool.

2024-03-05 03:37 UTC, rfrenchseti approved these changes

2024-03-05 03:37 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    config.read(default_config_file)
It turns out that `read` is designed to take a list of filenames, and doesn't give an error if they don't exist. But here we would really like it to give an error. At the very least if someone specifies a config file by hand, we should tell them if we failed to read it. So you need to use `read_file` as follows: `config.read_file(open(default_config_file))`

Same for the second `read` below.

Now as discussed elsewhere, it would be really nice to give a pleasant error message instead of just throwing an exception if the file doesn't exist, so perhaps something like:

```
try:
    config.read_file(open(default_config_file))
except OSError:
    print(error message here)
    sys.exit(1)
```

2024-03-05 03:37 UTC, rfrenchseti commented on indextools/pds4_create_xml_index.py
> +    """Create a config object from a given configuration file.
Comment needs to be updated to say we start with the default config file and then override with the specific config file, if provided.

2024-03-05 20:17 UTC, rfrenchseti approved these changes

2024-03-05 20:54 UTC, merged